### ISSUE TITLE
Confused by ignore syntax

### ISSUE THREAD

**Issue by emilbayes** [datproject/dat-ignore#3]
Just wanted to post a quick experience of using `.datignore`. I first tired having just `node_modules` in my `.datignore` like I do with `.gitignore`, but the directory was still being indexed. I  then tried `node_modules/*` as I sometimes do with `.gitignore` also, but it was still being indexed. Only `node_modules/**` worked, which I guess is technically the right way :)

Just something to consider for the future

**Comment by mafintosh** [comment]
We shoud support this use case for sure, you wanna PR a test case? (and fix if you are up for it)

**Comment by emilbayes** [comment]
Busy with some other stuff now, but maybe later. Just wanted to have it here for posterity

**Comment by joehand** [comment]
Ya it is confusing. Its the default for https://github.com/es128/anymatch, we could look at other string/glob path matching modules or change the default.

**Comment by pfrazee** [comment]
https://github.com/bmeck/dotignore might be the solution we need. It wraps anymatch with processing to match .gitignore's syntax

**Comment by jondashkyle** [comment]
Also find this a little confusing. That module @pfrazee would be a great improvement. Open for me to make a PR making that change?

**Comment by joehand** [comment]
@jondashkyle yes please! Haven't had time to get to this.
